export { Student } from './student.model';
export { Lecturer } from './lecturer.model';
export { Course } from './course.model';
export { Lecture } from './lecture.model';
export { Answer } from './answers.model';
export { Question } from './questions.model';
export { Test } from './test.model';
export { Enrollment } from './enrollment.model';
export { Assignment } from './assignment.model';
